# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/item.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/item.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/item.proto\x12\x04item\"\x0e\n\x0c\x45mptyRequest\"=\n\x0cItemResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"5\n\x10ItemListResponse\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.item.ItemResponse\"\x1c\n\x0eGetItemRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x85\x01\n\x0fItemGrpcService\x12;\n\x0bGetAllItems\x12\x12.item.EmptyRequest\x1a\x16.item.ItemListResponse\"\x00\x12\x35\n\x07GetItem\x12\x14.item.GetItemRequest\x1a\x12.item.ItemResponse\"\x00\x42+\n\x1c\x63om.example.javaservice.grpcB\tItemProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.item_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.example.javaservice.grpcB\tItemProtoP\001'
  _globals['_EMPTYREQUEST']._serialized_start=27
  _globals['_EMPTYREQUEST']._serialized_end=41
  _globals['_ITEMRESPONSE']._serialized_start=43
  _globals['_ITEMRESPONSE']._serialized_end=104
  _globals['_ITEMLISTRESPONSE']._serialized_start=106
  _globals['_ITEMLISTRESPONSE']._serialized_end=159
  _globals['_GETITEMREQUEST']._serialized_start=161
  _globals['_GETITEMREQUEST']._serialized_end=189
  _globals['_ITEMGRPCSERVICE']._serialized_start=192
  _globals['_ITEMGRPCSERVICE']._serialized_end=325
# @@protoc_insertion_point(module_scope)
