# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import item_pb2 as protos_dot_item__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/item_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ItemGrpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllItems = channel.unary_unary(
                '/item.ItemGrpcService/GetAllItems',
                request_serializer=protos_dot_item__pb2.EmptyRequest.SerializeToString,
                response_deserializer=protos_dot_item__pb2.ItemListResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/item.ItemGrpcService/GetItem',
                request_serializer=protos_dot_item__pb2.GetItemRequest.SerializeToString,
                response_deserializer=protos_dot_item__pb2.ItemResponse.FromString,
                _registered_method=True)


class ItemGrpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemGrpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllItems,
                    request_deserializer=protos_dot_item__pb2.EmptyRequest.FromString,
                    response_serializer=protos_dot_item__pb2.ItemListResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=protos_dot_item__pb2.GetItemRequest.FromString,
                    response_serializer=protos_dot_item__pb2.ItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'item.ItemGrpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('item.ItemGrpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ItemGrpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/item.ItemGrpcService/GetAllItems',
            protos_dot_item__pb2.EmptyRequest.SerializeToString,
            protos_dot_item__pb2.ItemListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/item.ItemGrpcService/GetItem',
            protos_dot_item__pb2.GetItemRequest.SerializeToString,
            protos_dot_item__pb2.ItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
