# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/user.proto\x12\x04user\"\x12\n\x10\x45mptyUserRequest\";\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"5\n\x10UserListResponse\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.user.UserResponse2R\n\x0fUserGrpcService\x12?\n\x0bGetAllUsers\x12\x16.user.EmptyUserRequest\x1a\x16.user.UserListResponse\"\x00\x42\x30\n!com.example.javaservice.grpc.userB\tUserProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.example.javaservice.grpc.userB\tUserProtoP\001'
  _globals['_EMPTYUSERREQUEST']._serialized_start=27
  _globals['_EMPTYUSERREQUEST']._serialized_end=45
  _globals['_USERRESPONSE']._serialized_start=47
  _globals['_USERRESPONSE']._serialized_end=106
  _globals['_USERLISTRESPONSE']._serialized_start=108
  _globals['_USERLISTRESPONSE']._serialized_end=161
  _globals['_USERGRPCSERVICE']._serialized_start=163
  _globals['_USERGRPCSERVICE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
